# Youtube Data Collection

## Objective

This notebook collects Youtube posts related to AI-generated Ghibli-style images using relevant keywords. The collected dataset will be used in the GenAI Carbon Footprint project for later analysis and comparison across multiple social media platforms.

**Keywords**

- ghibliart
- ghiblistyle
- ghiblistudio
- ghiblitrend

In [38]:
!pip -q install yt-dlp pandas

In [39]:
import yt_dlp
import pandas as pd

In [40]:
import yt_dlp

ydl_opts = {
    "quiet": True,
    "extract_flat": True,
}

with yt_dlp.YoutubeDL(ydl_opts) as ydl:
    results = ydl.extract_info(
        "ytsearch5:ghibliart",
        download=False
    )

print(results.keys())
print()

for video in results["entries"]:
    print(video.get("title"))

dict_keys(['id', 'title', '_type', 'entries', 'webpage_url', 'original_url', 'webpage_url_basename', 'webpage_url_domain', 'extractor', 'extractor_key', 'release_year', 'playlist_count', 'epoch'])

ASMR Anime Ghibli style Croissant 🥐 🥐 #anime #animation #ghibli #ghibliart #japanese #japanesefood
My Ghibli art #ghibli #ghibliart #ghiblistudio
How to make ghibli art for FREE | ghibli art tutorial | ghibli image generator #ghibli #ghibliart
Ghibli Landscape Painting | How to Paint in Ghibli Style | Ghibli Art Tutorial #painting #ghibliart
How to make ghibli art in chatgpt in 2 minutes #ghibliart#video#chatgpt

In [41]:
keywords = [
    "ghibliart",
    "ghiblistyle",
    "ghiblistudio",
    "ghiblitrend"
]

In [42]:
all_videos = []

ydl_opts = {
    "quiet": True,
    "extract_flat": True,
}

for keyword in keywords:

    print(f"Collecting: {keyword}")

    with yt_dlp.YoutubeDL(ydl_opts) as ydl:

        results = ydl.extract_info(
            f"ytsearch100:{keyword}",
            download=False
        )

        for video in results["entries"]:

            all_videos.append({
                "Keyword": keyword,
                "Video ID": video.get("id"),
                "Title": video.get("title"),
                "Uploader": video.get("channel"),
                "Upload Date": video.get("upload_date"),
                "Duration (sec)": video.get("duration"),
                "Views": video.get("view_count"),
                "Video URL": f"https://www.youtube.com/watch?v={video.get('id')}"
            })

print(f"\nCollected {len(all_videos)} videos.")

Collecting: ghibliart
Collecting: ghiblistyle
Collecting: ghiblistudio
Collecting: ghiblitrend

Collected 400 videos.

In [43]:
youtube_df = pd.DataFrame(all_videos)

print(f"Collected {len(youtube_df)} videos.")

display(youtube_df.head())

Collected 400 videos.

,Keyword,Video ID,Title,Uploader,Upload Date,Duration (sec),Views,Video URL
0,ghibliart,5GGd_RoTH9M,My Ghibli art #ghibli #ghibliart #ghiblistudio,Chloë’s,None,11,3,https://www.youtube.com/watch?v=5GGd_RoTH9M
1,ghibliart,wkuFaGX-_OE,ASMR Anime Ghibli style Croissant 🥐 🥐 #anime #...,Mini food art,None,32,1,https://www.youtube.com/watch?v=wkuFaGX-_OE
2,ghibliart,N00brUPfUkI,Ghibli Landscape Painting | How to Paint in Gh...,Artikate for Artists,None,196,248,https://www.youtube.com/watch?v=N00brUPfUkI
3,ghibliart,gmMyGDWoNFw,Create Ghibli-Style Art | Tutorial! | Notend V...,Notend vfx,None,79,20,https://www.youtube.com/watch?v=gmMyGDWoNFw
4,ghibliart,JlxkKS8-2ZE,Anxiety #ghibli #anxietyrelief #ghibliart,TheMentalBull,None,21,0,https://www.youtube.com/watch?v=JlxkKS8-2ZE

In [44]:
youtube_clean = youtube_df[[
    "Keyword",
    "Video ID",
    "Title",
    "Uploader",
    "Upload Date",
    "Duration (sec)",
    "Views",
    "Video URL"
]].copy()

youtube_clean.to_csv(
    "youtube_ghibli_posts.csv",
    index=False
)

print(f"Saved {len(youtube_clean)} videos.")

display(youtube_clean.head())

Saved 400 videos.

,Keyword,Video ID,Title,Uploader,Upload Date,Duration (sec),Views,Video URL
0,ghibliart,5GGd_RoTH9M,My Ghibli art #ghibli #ghibliart #ghiblistudio,Chloë’s,None,11,3,https://www.youtube.com/watch?v=5GGd_RoTH9M
1,ghibliart,wkuFaGX-_OE,ASMR Anime Ghibli style Croissant 🥐 🥐 #anime #...,Mini food art,None,32,1,https://www.youtube.com/watch?v=wkuFaGX-_OE
2,ghibliart,N00brUPfUkI,Ghibli Landscape Painting | How to Paint in Gh...,Artikate for Artists,None,196,248,https://www.youtube.com/watch?v=N00brUPfUkI
3,ghibliart,gmMyGDWoNFw,Create Ghibli-Style Art | Tutorial! | Notend V...,Notend vfx,None,79,20,https://www.youtube.com/watch?v=gmMyGDWoNFw
4,ghibliart,JlxkKS8-2ZE,Anxiety #ghibli #anxietyrelief #ghibliart,TheMentalBull,None,21,0,https://www.youtube.com/watch?v=JlxkKS8-2ZE

In [45]:
print("Dataset Shape:")
print(youtube_clean.shape)

print("\nColumns:")
print(youtube_clean.columns.tolist())

print("\nMissing Values:")
print(youtube_clean.isnull().sum())

youtube_clean.describe(include="all")

Dataset Shape:
(400, 8)

Columns:
['Keyword', 'Video ID', 'Title', 'Uploader', 'Upload Date', 'Duration (sec)', 'Views', 'Video URL']

Missing Values:
Keyword             0
Video ID            0
Title               0
Uploader            0
Upload Date       400
Duration (sec)      0
Views               0
Video URL           0
dtype: int64

,Keyword,Video ID,Title,Uploader,Upload Date,Duration (sec),Views,Video URL
count,400,400,400,400,0,400.000000,4.000000e+02,400
unique,4,393,383,309,0,NaN,NaN,393
top,ghibliart,5GGd_RoTH9M,Relaxing music without ads Ghibli Studio Ghibl...,Ghibli Music BGM,NaN,NaN,NaN,https://www.youtube.com/watch?v=5GGd_RoTH9M
freq,100,2,5,23,NaN,NaN,NaN,2
mean,NaN,NaN,NaN,NaN,NaN,2226.120000,4.159073e+05,NaN
std,NaN,NaN,NaN,NaN,NaN,4805.741076,1.955834e+06,NaN
min,NaN,NaN,NaN,NaN,NaN,7.000000,0.000000e+00,NaN
25%,NaN,NaN,NaN,NaN,NaN,143.500000,4.950000e+01,NaN
50%,NaN,NaN,NaN,NaN,NaN,363.000000,4.250000e+02,NaN
75%,NaN,NaN,NaN,NaN,NaN,1466.250000,3.020725e+04,NaN
max,NaN,NaN,NaN,NaN,NaN,38251.000000,2.202113e+07,NaN

In [46]:
print("=" * 60)
print("YouTube Dataset Summary")
print("=" * 60)

print(f"Total Videos Collected : {len(youtube_clean)}")
print(f"Unique Keywords Queried : {youtube_clean['Keyword'].nunique()}")

print("\nKeywords Queried:")

for keyword in sorted(youtube_clean["Keyword"].unique()):
    print("-", keyword)

print("\nDataset successfully collected and cleaned.")

============================================================
YouTube Dataset Summary
============================================================
Total Videos Collected : 400
Unique Keywords Queried : 4

Keywords Queried:
- ghibliart
- ghiblistudio
- ghiblistyle
- ghiblitrend

Dataset successfully collected and cleaned.